USE DATABASE BANKING_RAW;
CREATE SCHEMA CUSTOMER_DATA;
CREATE SCHEMA TRANSACTION_DATA;
CREATE SCHEMA EXTERNAL_DATA;

USE DATABASE BANKING_STAGING;
CREATE SCHEMA STG_CUSTOMER;
CREATE SCHEMA STG_TRANSACTIONS;
CREATE SCHEMA STG_RISK;

USE DATABASE BANKING_MARTS;
CREATE SCHEMA DIM_CUSTOMER;
CREATE SCHEMA FACT_TRANSACTIONS;
CREATE SCHEMA RISK_ANALYTICS;

USE DATABASE BANKING_ANALYTICS;
CREATE SCHEMA RISK_ANALYTICS;