CREATE VIEW BANKING_STAGING.STG_CUSTOMER.DATA_QUALITY_REPORT AS
SELECT 
    data_quality_flag,
    COUNT(*) as record_count,
    ROUND(COUNT(*) * 100.0 / SUM(COUNT(*)) OVER(), 2) as percentage
FROM BANKING_STAGING.STG_CUSTOMER.CUSTOMER_PROFILES_STG
GROUP BY data_quality_flag;
