-- Create roles hierarchy (add more as needed)
CREATE ROLE DATA_ANALYST;
CREATE ROLE DATA_SCIENTIST;
CREATE ROLE RISK_MANAGER;
CREATE ROLE COMPLIANCE_OFFICER;
CREATE ROLE DATA_ENGINEER;

-- Create functional roles
CREATE ROLE CUSTOMER_DATA_READER;
CREATE ROLE TRANSACTION_DATA_READER;
CREATE ROLE PII_DATA_READER;

-- Grant role hierarchy
GRANT ROLE CUSTOMER_DATA_READER TO ROLE DATA_ANALYST;
GRANT ROLE TRANSACTION_DATA_READER TO ROLE DATA_ANALYST;
GRANT ROLE DATA_ANALYST TO ROLE DATA_SCIENTIST;
GRANT ROLE PII_DATA_READER TO ROLE COMPLIANCE_OFFICER;

-- Grant database permissions
GRANT USAGE ON DATABASE BANKING_MARTS TO ROLE DATA_ANALYST;
GRANT USAGE ON SCHEMA BANKING_MARTS.DIM_CUSTOMER TO ROLE CUSTOMER_DATA_READER;
GRANT SELECT ON ALL TABLES IN SCHEMA BANKING_MARTS.DIM_CUSTOMER TO ROLE CUSTOMER_DATA_READER;