-- Create roles hierarchy (add more as needed)
CREATE ROLE IF NOT EXISTS DATA_ANALYST;
CREATE ROLE IF NOT EXISTS DATA_SCIENTIST;
CREATE ROLE IF NOT EXISTS RISK_MANAGER;
CREATE ROLE IF NOT EXISTS COMPLIANCE_OFFICER;
CREATE ROLE IF NOT EXISTS DATA_ENGINEER;
CREATE ROLE IF NOT EXISTS BUSINESS_USER;

-- Create functional roles
CREATE ROLE IF NOT EXISTS CUSTOMER_DATA_READER;
CREATE ROLE IF NOT EXISTS TRANSACTION_DATA_READER;
CREATE ROLE IF NOT EXISTS PII_DATA_READER;
CREATE ROLE IF NOT EXISTS ANALYTICS_READER;

-- Grant role hierarchy
GRANT ROLE CUSTOMER_DATA_READER TO ROLE DATA_ANALYST;
GRANT ROLE TRANSACTION_DATA_READER TO ROLE DATA_ANALYST;
GRANT ROLE ANALYTICS_READER TO ROLE DATA_ANALYST;

GRANT ROLE DATA_ANALYST TO ROLE DATA_SCIENTIST;
GRANT ROLE DATA_ANALYST TO ROLE RISK_MANAGER;

GRANT ROLE PII_DATA_READER TO ROLE COMPLIANCE_OFFICER;
GRANT ROLE DATA_ANALYST TO ROLE COMPLIANCE_OFFICER;

-- Grant database permissions
GRANT USAGE ON DATABASE BANKING_MARTS TO ROLE ANALYTICS_READER;
GRANT USAGE ON SCHEMA BANKING_MARTS.DIM_CUSTOMER TO ROLE CUSTOMER_DATA_READER;

-- Schema permissions
GRANT USAGE ON SCHEMA BANKING_MARTS.DIM_CUSTOMER TO ROLE CUSTOMER_DATA_READER;
GRANT USAGE ON SCHEMA BANKING_MARTS.FACT_TRANSACTIONS TO ROLE TRANSACTION_DATA_READER;
GRANT USAGE ON SCHEMA BANKING_ANALYTICS.RISK_ANALYTICS TO ROLE RISK_MANAGER;

-- Table permissions
GRANT SELECT ON ALL TABLES IN SCHEMA BANKING_MARTS.DIM_CUSTOMER TO ROLE CUSTOMER_DATA_READER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA BANKING_MARTS.FACT_TRANSACTIONS TO ROLE TRANSACTION_DATA_READER;
